### ISSUE TITLE
Automatic conversion of false to array is deprecated

### ISSUE THREAD

**Issue by SoloApoellin** [condor2/Opencart_2302_PHP_8#4]
Automatic conversion of false to array is deprecated in php >8.0
/catalog/model/catalog/product.php line 265

To fix that you have to add
$product_data = array();
above line 265

Thanks

**Comment by condor2** [comment]
https://github.com/condor2/Opencart_2302_PHP_8/commit/16a27a5cdcfb9ef7dac8234f603c4346a1ec12c7
